"""Export a calibrated `BalanceBotPolicyRef` to a Rust source file of
int8-weight / int16-activation Q-format arrays plus per-layer
requantization params, for consumption via
`embedded_nn::fully_connected::fully_connected_s16`.

embedded-nn has no LeakyReLU kernel (unlike `sigmoid_s16`/`tanh_s16`), so
the activation is emitted as a small hand-written int16 op in the generated
file itself: `x >= 0 ? x : (x * NEG_SLOPE_Q15) >> 15`. This reuses the same
per-tensor scale before and after the activation (no extra requant step),
which is valid because `|leaky_relu(x)| <= |x|` for the chosen slope.
"""

from __future__ import annotations

import numpy as np

from tools.quantize_export_balance_bot.calibrate import CalibrationStats
from tools.quantize_export_balance_bot.quantize import (
  calibrate_symmetric_scale,
  fc_s16_requant_params,
  quantize_bias_s64,
  quantize_weight_s8,
)
from tools.quantize_export_balance_bot.reference_model import (
  LEAKY_RELU_NEGATIVE_SLOPE,
  BalanceBotPolicyRef,
)

NEG_SLOPE_Q15 = round(LEAKY_RELU_NEGATIVE_SLOPE * 32768)


def _fmt_i8_array(name: str, values: np.ndarray) -> str:
  flat = ", ".join(str(int(v)) for v in values.flatten())
  return f"pub static {name}: [i8; {values.size}] = [{flat}];\n"


def _fmt_i64_array(name: str, values: np.ndarray) -> str:
  flat = ", ".join(str(int(v)) for v in values.flatten())
  return f"pub static {name}: [i64; {values.size}] = [{flat}];\n"


def _export_layer(
  prefix: str, layer, input_scale: float, output_scale: float
) -> str:
  weight = layer.weight.detach().numpy()  # [out, in], row-major.
  weight_scale = calibrate_symmetric_scale(weight, num_bits=8)
  q_weight = quantize_weight_s8(weight, weight_scale)
  multiplier, shift = fc_s16_requant_params(input_scale, weight_scale, output_scale)
  out_dim, in_dim = weight.shape

  bias = layer.bias.detach().numpy()
  q_bias = quantize_bias_s64(bias, input_scale, weight_scale)

  lines = [
    f"// {prefix}: Linear({in_dim} -> {out_dim}), input_scale={input_scale:.8g}, "
    f"weight_scale={weight_scale:.8g}, output_scale={output_scale:.8g}",
    _fmt_i8_array(f"{prefix}_WEIGHT", q_weight),
    _fmt_i64_array(f"{prefix}_BIAS", q_bias),
    f"pub const {prefix}_IN_DIM: usize = {in_dim};",
    f"pub const {prefix}_OUT_DIM: usize = {out_dim};",
    f"pub const {prefix}_MULTIPLIER: i32 = {multiplier};",
    f"pub const {prefix}_SHIFT: i32 = {shift};",
    "",
  ]
  return "\n".join(lines)


def export_policy_weights_rs(model: BalanceBotPolicyRef, stats: CalibrationStats) -> str:
  obs_scale = max(stats.obs_absmax / 32767.0, 1e-8)
  fc1_scale = max(stats.fc1_absmax / 32767.0, 1e-8)
  fc2_scale = max(stats.fc2_absmax / 32767.0, 1e-8)
  fc3_scale = max(stats.fc3_absmax / 32767.0, 1e-8)
  action_scale = max(stats.action_absmax / 32767.0, 1e-8)

  chunks = [
    "// AUTO-GENERATED by tools/quantize_export_balance_bot/export_rust.py. "
    "Do not edit by hand.",
    "#![allow(clippy::all)]",
    "",
    f"pub const OBS_SCALE: f32 = {obs_scale:.8g};",
    f"pub const FC1_OUT_SCALE: f32 = {fc1_scale:.8g};",
    f"pub const FC2_OUT_SCALE: f32 = {fc2_scale:.8g};",
    f"pub const FC3_OUT_SCALE: f32 = {fc3_scale:.8g};",
    f"pub const ACTION_SCALE: f32 = {action_scale:.8g};",
    f"pub const NEG_SLOPE_Q15: i32 = {NEG_SLOPE_Q15};  // LeakyReLU negative slope.",
    "",
    "/// `x >= 0 ? x : (x * NEG_SLOPE_Q15) >> 15`, same scale in and out.",
    "pub fn leaky_relu_i16(x: i16) -> i16 {",
    "    if x >= 0 {",
    "        x",
    "    } else {",
    "        ((x as i32 * NEG_SLOPE_Q15) >> 15) as i16",
    "    }",
    "}",
    "",
    _export_layer("FC1", model.fc1, obs_scale, fc1_scale),
    _export_layer("FC2", model.fc2, fc1_scale, fc2_scale),
    _export_layer("FC3", model.fc3, fc2_scale, fc3_scale),
    _export_layer("FC_OUT", model.fc_out, fc3_scale, action_scale),
  ]
  return "\n".join(chunks)
